routes/web.php
<?php


use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TermController;
use App\Http\Controllers\MarkController; 

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::prefix('admin')->group(function () {}); // if we want prefix after domain, place inside the below code.
Route::group(['middleware' => 'auth:web'], function () {
    Route::resource('teachers', TeacherController::class);
    Route::resource('students', StudentController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('terms', TermController::class);
    Route::resource('marks', MarkController::class);  
});

resources/views/admin/marks.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-1 mb-1">Marks </h4>
    <div class="row">
        <div class="col-md-12"> 
            <div class="card mb-4">
                
                @if(isset($mark))
                <h5 class="card-header">EDIT</h5>
                @else
                <h5 class="card-header">ADD NEW</h5>
                @endif
                <!-- Account -->
                <div class="card-body">
                    @if (\Session::has('msg'))
                        <div class="alert alert-success">
                            {!! \Session::get('msg') !!}</li> 
                        </div>
                    @endif
                    @if(isset($mark))
                        {{ Form::model($mark, ['route' => ['marks.update', $mark->id], 'method' => 'patch']) }}
                        @csrf
                        <div class="row">
                            <div class="row">
                                <div class="mb-3 col-md-6">
                                    <label for="name" class="form-label"> Name</label>
                                     <select name="student_id" id="" class="form-control">
                                        <option value="">-Select a Student-</option>
                                        @foreach ($students as $student)
                                            <option value="{{$student->id}}" selected>{{$student->name}}</option>
                                        @endforeach
                                     </select>
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label for="name" class="form-label"> Term</label>
                                    <select name="term_id" id="" class="form-control">
                                        <option value="">-Select a Term-</option>
                                        @foreach ($terms as $term)
                                            <option value="{{$term->id}}" selected>{{$term->name}}</option>
                                        @endforeach
                                     </select>
                                </div>
                                
                                <div class="card">
                                    <div class="card-title">
                                        MARKS
                                    </div>
                                    <table class="table table-striped table-dark table-bordered">
                                    <thead>
                                      <tr>
                                        <th scope="col">SUBJECTS</th>
                                        <th scope="col">MARKS</th> 
                                      </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($subjects as $subject)
                                            <tr>
                                                <th scope="row"><input type="hidden" class="form-control subject_id" name="subject_id[]" value="{{$subject->id}}">{{$subject->name}}</th>
                                                <td><input type="text"  name="marks[]" class="form-control marks" value=""></td> 
                                            </tr>
                                        @endforeach 
                                    </tbody>
                                  </table>
                                </div> 
                                </div> 
                            </div> 
                            <div class="mt-2">
                                <button type="submit" onClick="$(this).text('Loading..')" class="btn btn-primary me-2">Save</button> 
                                <a  href="{{ route('marks.index') }}" class="btn btn-danger me-2">Cancel</a>
                            </div>
                        </div> 
                        {{ Form::close() }}
                    @else 
                    <form id="formAccountSettings" method="POST" class=".markEntryForm">
                        @csrf
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                 <select name="student_id" id="" class="form-control">
                                    <option value="">-Select a Student-</option>
                                    @foreach ($students as $student)
                                        <option value="{{$student->id}}" selected>{{$student->name}}</option>
                                    @endforeach
                                 </select>
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Term</label>
                                <select name="term_id" id="" class="form-control">
                                    <option value="">-Select a Term-</option>
                                    @foreach ($terms as $term)
                                        <option value="{{$term->id}}" selected>{{$term->name}}</option>
                                    @endforeach
                                 </select>
                            </div>
                            
                            <div class="card">
                                <div class="card-title">
                                    MARKS
                                </div>
                                <table class="table table-striped table-dark table-bordered">
                                <thead>
                                  <tr>
                                    <th scope="col">SUBJECTS</th>
                                    <th scope="col">MARKS</th> 
                                  </tr>
                                </thead>
                                <tbody>
                                    @foreach ($subjects as $subject)
                                        <tr>
                                            <th scope="row"><input type="hidden" class="form-control subject_id" name="subject_id[]" value="{{$subject->id}}">{{$subject->name}}</th>
                                            <td><input type="text"  name="marks[]" class="form-control marks" value=""></td> 
                                        </tr>
                                    @endforeach 
                                </tbody>
                              </table>
                            </div>
                                
                                 
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2 createMarkButton">Save</button> 
                            </div>
                        </div> 
                    </form>
                    @endif
                </div>
                <hr class="my-0" />
                <div class="card-body">
                    <div class="table-responsive text-nowrap">
                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <tr> 
                                    <th class="text-white">ID</th> 
                                    <th class="text-white">NAME</th> 
                                    @foreach ($subjects as $subject)
                                    <th class="text-white">{{$subject->name}}</th>   
                                    @endforeach
                                    <th class="text-white">Total</th>
                                    <th class="text-white">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0 markLoopSection">
                                @foreach ($marksList as $mark)
                                <tr> 
                                    <td>{{ $mark->id }}</td>
                                    <td>{{ $mark->student->name }}</td>
                                    @php $total=0; @endphp
                                    @foreach($mark->mark_items as $item) 
                                    @php $total = isset($item->marks) ? $total+($item->marks) :'' @endphp
                                    <td>{{isset($item->marks)?$item->marks:''}}</td>
                                    @endforeach
                                    <td>{{$total}}</td>
                                    <td>
                                        <a class="btn btn-sm btn-primary text-white" href="{{ route('marks.edit',$mark->id )}}" ><i class="bx bx-edit-alt me-1"></i> Edit</a >
                                        <a class="btn btn-sm btn-danger text-white deleteActionbutton" data-table="marks" data-id="{{ $mark->id }}"><i class="bx bx-trash me-1"></i> Delete</a >
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /Account -->
            </div>
            
        </div>
    </div>
</div> 
@endsection

resources/views/admin/students.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> students</h4>
    <div class="row">
        <div class="col-md-12">
            @include('admin.layouts.nav_items')
            <div class="card mb-4">
                
                @if(isset($student))
                <h5 class="card-header">EDIT</h5>
                @else
                <h5 class="card-header">ADD NEW</h5>
                @endif
                <!-- Account -->
                <div class="card-body">
                    @if (\Session::has('msg'))
                        <div class="alert alert-success">
                            {!! \Session::get('msg') !!}</li> 
                        </div>
                    @endif
                    @if(isset($student))
                        {{ Form::model($student, ['route' => ['students.update', $student->id], 'method' => 'patch']) }}
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="name" value="{{ $student->name }}" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Age</label>
                                <input class="form-control" type="text" id="name" name="age" value="{{ $student->age }}" placeholder="Enter Age" autofocus />
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Gender</label>
                                <select name="gender" id="" class="form-control">
                                    <option value="">-Select a gender-</option>  
                                     <option value="Male" {{ ($student->gender == 'Male') ? 'selected' :'' }}>Male</option>
                                     <option value="Female" {{ ($student->gender == 'Female') ? 'selected' :'' }}>Female</option>
                                     <option value="Others" {{ ($student->gender == 'Others') ? 'selected' :'' }}>Others</option>
                                </select> 
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Teachers</label>
                                <select name="teacher_id" id="" class="form-control">
                                    <option value="">-Select a teacher-</option>  
                                    @foreach ($teachers as $teacher)
                                      <option value="{{$teacher->id}}" {{ ($student->teacher_id == $teacher->id) ? 'selected' :'' }}>{{$teacher->name}}</option>
                                    @endforeach
                                </select> 
                            </div>
                            <div class="mt-2">
                                <button type="submit" onClick="$(this).text('Loading..')" class="btn btn-primary me-2">Save</button> 
                                <a  href="{{ route('students.index') }}" class="btn btn-danger me-2">Cancel</a>
                            </div>
                        </div> 
                        {{ Form::close() }}
                    @else 
                    <form id="formAccountSettings" method="POST" >
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="name" value="" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Age</label>
                                <input class="form-control" type="text" id="name" name="age" value="" placeholder="Enter Age" autofocus />
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Gender</label>
                                <select name="gender" id="" class="form-control">
                                    <option value="">-Select a gender-</option>  
                                     <option value="Male">Male</option>
                                     <option value="Female">Female</option>
                                     <option value="Others">Others</option>
                                </select> 
                            </div>
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Teachers</label>
                                <select name="teacher_id" id="" class="form-control">
                                    <option value="">-Select a teacher-</option>  
                                    @foreach ($teachers as $teacher)
                                      <option value="{{$teacher->id}}">{{$teacher->name}}</option>
                                    @endforeach
                                </select> 
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2 createStudentButton">Save</button> 
                            </div>
                        </div> 
                    </form>
                    @endif
                </div>
                <hr class="my-0" />
                <div class="card-body">
                    <div class="table-responsive text-nowrap">
                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <tr> 
                                    <th class="text-white">student</th> 
                                    <th class="text-white">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0 studentLoopSection">
                                @include('admin.loops.student') 
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /Account -->
            </div>
            
        </div>
    </div>
</div> 
@endsection

resources/views/admin/subjects.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Subjects</h4>
    <div class="row">
        <div class="col-md-12">
            @include('admin.layouts.nav_items')
            <div class="card mb-4">
                
                @if(isset($subject))
                <h5 class="card-header">EDIT</h5>
                @else
                <h5 class="card-header">ADD NEW</h5>
                @endif
                <!-- Account -->
                <div class="card-body">
                    @if (\Session::has('msg'))
                        <div class="alert alert-success">
                            {!! \Session::get('msg') !!}</li> 
                        </div>
                    @endif
                    @if(isset($subject))
                        {{ Form::model($subject, ['route' => ['subjects.update', $subject->id], 'method' => 'patch']) }}
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="subject" value="{{ $subject->name }}" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mt-2">
                                <button type="submit" onClick="$(this).text('Loading..')" class="btn btn-primary me-2">Save</button> 
                                <a  href="{{ route('subjects.index') }}" class="btn btn-danger me-2">Cancel</a>
                            </div>
                        </div> 
                        {{ Form::close() }}
                    @else 
                    <form id="formAccountSettings" method="POST" >
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="name" value="" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2 createSubjectButton">Save</button> 
                            </div>
                        </div> 
                    </form>
                    @endif
                </div>
                <hr class="my-0" />
                <div class="card-body">
                    <div class="table-responsive text-nowrap">
                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <tr> 
                                    <th class="text-white">subject</th> 
                                    <th class="text-white">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0 subjectLoopSection">
                                @include('admin.loops.subject') 
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /Account -->
            </div>
            
        </div>
    </div>
</div> 
@endsection

resources/views/admin/teachers.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Teachers</h4>
    <div class="row">
        <div class="col-md-12">
            @include('admin.layouts.nav_items')
            <div class="card mb-4">
                
                @if(isset($teacher))
                <h5 class="card-header">EDIT</h5>
                @else
                <h5 class="card-header">ADD NEW</h5>
                @endif
                <!-- Account -->
                <div class="card-body">
                    @if (\Session::has('msg'))
                        <div class="alert alert-success">
                            {!! \Session::get('msg') !!}</li> 
                        </div>
                    @endif
                    @if(isset($teacher))
                        {{ Form::model($teacher, ['route' => ['teachers.update', $teacher->id], 'method' => 'patch']) }}
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="teacher" value="{{ $teacher->name }}" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mt-2">
                                <button type="submit" onClick="$(this).text('Loading..')" class="btn btn-primary me-2">Save</button> 
                                <a  href="{{ route('teachers.index') }}" class="btn btn-danger me-2">Cancel</a>
                            </div>
                        </div> 
                        {{ Form::close() }}
                    @else 
                    <form id="formAccountSettings" method="POST" >
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="name" value="" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2 createTeacherButton">Save</button> 
                            </div>
                        </div> 
                    </form>
                    @endif
                </div>
                <hr class="my-0" />
                <div class="card-body">
                    <div class="table-responsive text-nowrap">
                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <tr> 
                                    <th class="text-white">Teacher</th> 
                                    <th class="text-white">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0 teacherLoopSection">
                                @include('admin.loops.teacher') 
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /Account -->
            </div>
            
        </div>
    </div>
</div> 
@endsection

resources/views/admin/terms.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Settings /</span> Terms</h4>
    <div class="row">
        <div class="col-md-12">
            @include('admin.layouts.nav_items')
            <div class="card mb-4">
                
                @if(isset($term))
                <h5 class="card-header">EDIT</h5>
                @else
                <h5 class="card-header">ADD NEW</h5>
                @endif
                <!-- Account -->
                <div class="card-body">
                    @if (\Session::has('msg'))
                        <div class="alert alert-success">
                            {!! \Session::get('msg') !!}</li> 
                        </div>
                    @endif
                    @if(isset($term))
                        {{ Form::model($term, ['route' => ['terms.update', $term->id], 'method' => 'patch']) }}
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="term" value="{{ $term->name }}" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mt-2">
                                <button type="submit" onClick="$(this).text('Loading..')" class="btn btn-primary me-2">Save</button> 
                                <a  href="{{ route('terms.index') }}" class="btn btn-danger me-2">Cancel</a>
                            </div>
                        </div> 
                        {{ Form::close() }}
                    @else 
                    <form id="formAccountSettings" method="POST" >
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label for="name" class="form-label"> Name</label>
                                <input class="form-control" type="text" id="name" name="name" value="" placeholder="Enter Name" autofocus />
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary me-2 createTermButton">Save</button> 
                            </div>
                        </div> 
                    </form>
                    @endif
                </div>
                <hr class="my-0" />
                <div class="card-body">
                    <div class="table-responsive text-nowrap">
                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <tr> 
                                    <th class="text-white">term</th> 
                                    <th class="text-white">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0 termLoopSection">
                                @include('admin.loops.term') 
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /Account -->
            </div>
            
        </div>
    </div>
</div> 
@endsection

resources/views/admin/toast.blade.php
@component('admin.component.toaster')
@slot('toaster_id')  @endslot
@slot('toaster_title')   @endslot
@slot('toaster_content')  @endslot
@endcomponent