routes/web.php
<?php


use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TermController;
use App\Http\Controllers\MarkController; 

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 
Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::prefix('admin')->group(function () {}); // if we want prefix after domain, place inside the below code.
Route::group(['middleware' => 'auth:web'], function () {
    Route::resource('teachers', TeacherController::class);
    Route::resource('students', StudentController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('terms', TermController::class);
    Route::resource('marks', MarkController::class);  
});

resources/views/admin/loops/mark.blade.php
{{-- @forelse ($marksList as $mark)
<tr> 
    <td>{{ $mark->name }}</td> 
    <td>{{$mark->mark_items}}</td>
    <td>
        <a class="btn btn-sm btn-primary text-white" href="{{ route('terms.edit',$mark->id )}}" ><i class="bx bx-edit-alt me-1"></i> Edit</a >
        <a class="btn btn-sm btn-danger text-white deleteActionbutton" data-table="terms" data-id="{{ $mark->id }}"><i class="bx bx-trash me-1"></i> Delete</a >
    </td>
</tr>
@empty
<tr> 
    <td colspan="{{ count($subjects)+2 }}" class="emptyTd text-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"  style="fill: rgb(80, 78, 78);transform: ;msFilter:;"><path d="M11.953 2C6.465 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.493 2 11.953 2zM12 20c-4.411 0-8-3.589-8-8s3.567-8 7.953-8C16.391 4 20 7.589 20 12s-3.589 8-8 8z"></path><path d="M11 7h2v7h-2zm0 8h2v2h-2z"></path></svg> No related records found ! </td>     
</tr>
@endforelse   --}}

resources/views/admin/loops/student.blade.php
@forelse ($studentsList as $student)
<tr> 
    <td>{{ $student->name }}</td> 
    <td>
        <a class="btn btn-sm btn-primary text-white" href="{{ route('students.edit',$student->id )}}" ><i class="bx bx-edit-alt me-1"></i> Edit</a >
        <a class="btn btn-sm btn-danger text-white deleteActionbutton" data-table="students" data-id="{{ $student->id }}"><i class="bx bx-trash me-1"></i> Delete</a >
    </td>
</tr>
@empty
<tr> 
    <td colspan="2" class="emptyTd text-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"  style="fill: rgb(80, 78, 78);transform: ;msFilter:;"><path d="M11.953 2C6.465 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.493 2 11.953 2zM12 20c-4.411 0-8-3.589-8-8s3.567-8 7.953-8C16.391 4 20 7.589 20 12s-3.589 8-8 8z"></path><path d="M11 7h2v7h-2zm0 8h2v2h-2z"></path></svg> No related records found ! </td>     
</tr>
@endforelse  

resources/views/admin/loops/subject.blade.php
@forelse ($subjectsList as $subject)
<tr> 
    <td>{{ $subject->name }}</td> 
    <td>
        <a class="btn btn-sm btn-primary text-white" href="{{ route('subjects.edit',$subject->id )}}" ><i class="bx bx-edit-alt me-1"></i> Edit</a >
        <a class="btn btn-sm btn-danger text-white deleteActionbutton" data-table="subjects" data-id="{{ $subject->id }}"><i class="bx bx-trash me-1"></i> Delete</a >
    </td>
</tr>
@empty
<tr> 
    <td colspan="2" class="emptyTd text-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"  style="fill: rgb(80, 78, 78);transform: ;msFilter:;"><path d="M11.953 2C6.465 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.493 2 11.953 2zM12 20c-4.411 0-8-3.589-8-8s3.567-8 7.953-8C16.391 4 20 7.589 20 12s-3.589 8-8 8z"></path><path d="M11 7h2v7h-2zm0 8h2v2h-2z"></path></svg> No related records found ! </td>     
</tr>
@endforelse  

resources/views/admin/loops/teacher.blade.php
@forelse ($teachersList as $teacher)
<tr> 
    <td>{{ $teacher->name }}</td> 
    <td>
        <a class="btn btn-sm btn-primary text-white" href="{{ route('teachers.edit',$teacher->id )}}" ><i class="bx bx-edit-alt me-1"></i> Edit</a >
        <a class="btn btn-sm btn-danger text-white deleteActionbutton" data-table="teachers" data-id="{{ $teacher->id }}"><i class="bx bx-trash me-1"></i> Delete</a >
    </td>
</tr>
@empty
<tr> 
    <td colspan="2" class="emptyTd text-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"  style="fill: rgb(80, 78, 78);transform: ;msFilter:;"><path d="M11.953 2C6.465 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.493 2 11.953 2zM12 20c-4.411 0-8-3.589-8-8s3.567-8 7.953-8C16.391 4 20 7.589 20 12s-3.589 8-8 8z"></path><path d="M11 7h2v7h-2zm0 8h2v2h-2z"></path></svg> No related records found ! </td>     
</tr>
@endforelse  

resources/views/admin/loops/term.blade.php
@forelse ($termsList as $term)
<tr> 
    <td>{{ $term->name }}</td> 
    <td>
        <a class="btn btn-sm btn-primary text-white" href="{{ route('terms.edit',$term->id )}}" ><i class="bx bx-edit-alt me-1"></i> Edit</a >
        <a class="btn btn-sm btn-danger text-white deleteActionbutton" data-table="terms" data-id="{{ $term->id }}"><i class="bx bx-trash me-1"></i> Delete</a >
    </td>
</tr>
@empty
<tr> 
    <td colspan="2" class="emptyTd text-center"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"  style="fill: rgb(80, 78, 78);transform: ;msFilter:;"><path d="M11.953 2C6.465 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.493 2 11.953 2zM12 20c-4.411 0-8-3.589-8-8s3.567-8 7.953-8C16.391 4 20 7.589 20 12s-3.589 8-8 8z"></path><path d="M11 7h2v7h-2zm0 8h2v2h-2z"></path></svg> No related records found ! </td>     
</tr>
@endforelse  